### ISSUE TITLE
Logic issue and sending extra props

### ISSUE THREAD

**Issue by jessicafarias** [trekab/react-calculator#10]
Hello, @trekab! Nice to have you as TSE.
I was watching through your code and I found you are sending 3 props to the Display component, but inside Display, you are using only the "result" prop. The "next" and "operation" props are unused inside Display component).

```
<Display result={total} next={next} operation={operation} />
const Display = ({ result }) => (...).
```

It wasn't an explicit requirement but you can try to improve your project to make it work with more than 2 numbers. for example in your calculator: 2+2=4 (it works properly) but when you consequently type 2 + 2 + 2 = 2 (it should display = 6 but is not working as a regular calculator does.)

Regards!

**Comment by trekab** [comment]
Wow! Thanks for catching that bug with my code @jessicafarias! I am honored that you took the time to review my code :pray: I will look into fixing that bug ASAP! Thank you for this great feedback!
